<?php

return [
    'site_url' => env('SEO_SITE_URL', 'https://tuvangiaxelexus.com'),
    'site_name' => env('SEO_SITE_NAME', 'Lexus Thăng Long'),

    'tracking' => [
        'gtm_id' => env('GTM_ID'),
        'ga4_id' => env('GA4_ID'),
        'gads_id' => env('GADS_ID'),
    ],
    'default_locale' => 'vi_VN',
    'default_title' => 'Tư Vấn Mua Xe Lexus Chính Hãng | Lexus Thăng Long Hà Nội',
    'default_description' => 'Đại lý ủy quyền chính hãng Lexus Thăng Long. Tư vấn giá lăn bánh, ưu đãi mới nhất các dòng RX, NX, ES, LX, LS, LM, GX. Hotline: 0962.896.582',
    'default_keywords' => 'Lexus Thăng Long, mua xe Lexus, giá xe Lexus, RX 500h, NX 350h, ES 300h, LX 600, đại lý Lexus Hà Nội',
    'default_og_image' => '/web/assets/images/lexus_logo.png',

    'organization' => [
        'name' => 'Lexus Thăng Long',
        'legal_name' => 'Đại lý ủy quyền Lexus Thăng Long',
        'phone' => '+84962896582',
        'phone_display' => '0962.896.582',
        'email' => 'contact@tuvangiaxelexus.com',
        'street' => 'Ngã tư Phạm Hùng giao Dương Đình Nghệ',
        'locality' => 'Mễ Trì, Nam Từ Liêm',
        'region' => 'Hà Nội',
        'country' => 'VN',
        'postal_code' => '100000',
        'lat' => 21.014722,
        'lng' => 105.781944,
        'opens' => '08:00',
        'closes' => '18:00',
        'rating_value' => '4.9',
        'review_count' => '2500',
        'social' => [
            'https://facebook.com/lexusthanglong',
            'https://youtube.com/@lexusthanglong',
        ],
    ],

    'cars' => [
        'rx' => [
            'name' => 'Lexus RX',
            'model' => 'RX 500h F SPORT Performance',
            'model_year' => '2026',
            'price' => '4490000000',
            'fuel' => 'Hybrid',
            'engine' => '2.4L Turbo Hybrid',
            'image' => '/web/assets/images/rx500hfsport.webp',
            'description' => 'Lexus RX 500h F SPORT Performance 2026 - SUV hybrid hiệu năng cao, công suất 366 HP.',
        ],
        'nx' => [
            'name' => 'Lexus NX',
            'model' => 'NX 350h Hybrid',
            'model_year' => '2026',
            'price' => '2750000000',
            'fuel' => 'Hybrid',
            'engine' => '2.5L Hybrid',
            'image' => '/web/assets/images/nx350h.jpeg',
            'description' => 'Lexus NX 350h 2026 - SUV hybrid hạng sang cỡ trung, công suất 188 HP.',
        ],
        'es' => [
            'name' => 'Lexus ES',
            'model' => 'ES 350h Hybrid',
            'model_year' => '2026',
            'price' => '2540000000',
            'fuel' => 'Hybrid',
            'engine' => '2.5L Hybrid e-CVT AWD',
            'image' => '/web/assets/images/es/mau-trang.jpg',
            'description' => 'Lexus ES 350h 2026 thế hệ 8 - Sedan hạng sang hybrid e-CVT AWD.',
        ],
        'ls' => [
            'name' => 'Lexus LS',
            'model' => 'LS 500h',
            'model_year' => '2026',
            'price' => '8200000000',
            'fuel' => 'Hybrid',
            'engine' => '3.5L V6 Hybrid',
            'image' => '/web/assets/images/lexus_logo.png',
            'description' => 'Lexus LS 500h 2026 - Sedan flagship hạng sang hybrid.',
        ],
        'lx' => [
            'name' => 'Lexus LX',
            'model' => 'LX 600',
            'model_year' => '2026',
            'price' => '8520000000',
            'fuel' => 'Xăng',
            'engine' => '3.5L V6 Twin-Turbo',
            'image' => '/web/assets/images/lexus_logo.png',
            'description' => 'Lexus LX 600 2026 - SUV full-size hạng sang flagship.',
        ],
        'lm' => [
            'name' => 'Lexus LM',
            'model' => 'LM 350h',
            'model_year' => '2026',
            'price' => '7200000000',
            'fuel' => 'Hybrid',
            'engine' => '2.5L Hybrid',
            'image' => '/web/assets/images/lexus_logo.png',
            'description' => 'Lexus LM 350h 2026 - MPV hạng sang dành cho doanh nhân.',
        ],
        'gx' => [
            'name' => 'Lexus GX',
            'model' => 'GX 550',
            'model_year' => '2026',
            'price' => '5690000000',
            'fuel' => 'Xăng',
            'engine' => '3.4L V6 Twin-Turbo',
            'image' => '/web/assets/images/lexus_logo.png',
            'description' => 'Lexus GX 550 2026 - SUV body-on-frame off-road hạng sang.',
        ],
    ],
];
